build: change pattern to monorepo

diff --git a/.github/workflows/test-flow.yaml b/.github/workflows/test-flow.yaml
--- a/.github/workflows/test-flow.yaml
+++ b/.github/workflows/test-flow.yaml
@@ -29,35 +29,108 @@ jobs:
       - uses: actions/setup-node@v6
         with:
           node-version: ${{ matrix.node-version }}
-          cache: "npm"
-          cache-dependency-path: package-lock.json
+          cache: 'yarn'
+          cache-dependency-path: yarn.lock
       - name: install
         run: |
-          npm ci
-      - name: commit-linting
-        run: |
-          if [[ "${{ github.base_ref }}" != "" ]]; then
-            echo "Setting up git environment for commitlint of pull request"
-            git fetch origin ${{ github.base_ref }}
-            git fetch origin ${{ github.head_ref }}
-            npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
-          else
-            echo "Setting up git environment for commitlint of branch push"
-            git fetch origin ${{ github.ref_name }} --unshallow
-            npx commitlint --from $(git rev-list --max-parents=0 origin/${{ github.ref_name }})
-          fi
+          yarn install --immutable
       - name: build
         run: |
-          npm run build
-      - name: linting
+          yarn build
+      - name: linting and formatting check
         run: |
-          npm run lint
-          npx prettier . --check
-      # Add git config user for some intgration testing
-      - name: setup git
-        run: |
-          git config --global user.name github-int-test
-          git config --global user.email github-int-test@github.com
+          yarn check
       - name: testing
         run: |
-          npm run test
+          yarn test
+  # Currently, we're not running pkg test for pulumi at this moment
+  # pkg-test:
+  #   needs:
+  #     - ci-checks
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node-version: [18.x, 20.x]
+  #       # mac runners seem to stall too often - leaving off and assuming unix works well
+  #       os: ['ubuntu-latest', 'windows-latest']
+  #       pkgManager: ['yarn-v1', 'yarn-berry', 'pnpm', 'npm']
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #         cache-dependency-path: yarn.lock
+  #     - name: install
+  #       run: |
+  #         npm install --force -g corepack@>=0.31.0
+  #         corepack enable
+  #         yarn install --immutable
+  #     - name: Restore dist
+  #       uses: actions/cache/restore@v4
+  #       with:
+  #         path: |
+  #           dist/
+  #         key: dist2-${{ github.sha }}
+  #         enableCrossOsArchive: true
+  #     - id: pkgtest-setup
+  #       uses: hanseltimeindustries/pkgtest-setup-action@v1
+  #     - name: pkgtest ${{ matrix.pkgManager }}
+  #       run: |
+  #         # This avoids yarnv1 level failures due to global cache lock issues
+  #         # Just preps by filling the cache in a synchronous manner
+  #         # No need to clean up since the container will do that on close
+  #         yarn pkgtest -p 1 --noYarnv1CacheClean --pkgManager ${{ matrix.pkgManager }} --collectLogFilesOn error --collectLogFilesStage tests --onWindowsProblems skip
+  #       # Collect any logs from the --collectLogFilesOn error to troubleshoot failures
+  #     - name: Archive logs on failure
+  #       if: failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: pkgtest-log-files-${{ matrix.pkgManager }}-${{ matrix.os }}-${{ matrix.node-version }}
+  #         path: ${{ steps.pkgtest-setup.outputs.collet_log_file_folder }}
+  #         retention-days: 1
+  #         include-hidden-files: true
+  # ensure-docs:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     # TODO: caching this action would accelerate the run
+  #     - name: corepack
+  #       run: |
+  #         corepack enable
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: ${{ matrix.node-version }}
+  #         cache: 'yarn'
+  #         cache-dependency-path: yarn.lock
+  #     - name: install
+  #       run: |
+  #         yarn install --immutable
+  #     - name: build
+  #       run: |
+  #         yarn build
+  #     - name: generate typedoc
+  #       run: |
+  #         yarn typedoc
+  #     - name: ensure no uncommitted docs
+  #       shell: bash
+  #       run: |
+  #         git diff
+  #         changes=$(git status --porcelain=v1 2>/dev/null)
+  #         if [ ! -z "$changes" ]; then
+  #             echo "Found typedoc generated files that weren't commited!"
+  #             echo "Please run 'yarn typedoc', and commit the files"
+  #             echo "$changes"
+  #             exit 1
+  #         fi
+  # easy to require end cap job
+  done:
+    needs:
+      # - ensure-docs
+      - ci-checks
+      # - pkg-test
+    runs-on: ubuntu-latest
+    name: Done
+    steps:
+      - run: exit 1
+        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
